#!/bin/bash

zk0=0
zk1=0
zk2=0
while [ $((zk0+zk1+zk2)) -lt 3 ]; do
    if ping -c 1 zookeeper-0; then zk0=1; fi
    if ping -c 1 zookeeper-1; then zk1=1; fi
    if ping -c 1 zookeeper-2; then zk2=1; fi
    echo "zk0=$zk0"
    echo "zk1=$zk1"
    echo "zk2=$zk2"
    sleep 2
done

exec /opt/zookeeper/bin/zkServer.sh start-foreground
