dokreg:
  hostname: dokreg
  environment: [CONSUL_CLIENT=consulclient, SERVICE=dokreg, DATA_CENTER=dev]
  user: root
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - consulclient:consulclient
  image: dokreg

consulserver:
  hostname: consulserver
  environment: [BOOTSTRAP_EXPECT=1, CONSUL_MODE=server, SERVICE=consulserver, DATA_CENTER=dev]
  ports:
    - "53/tcp"
    - "53/udp"
    - "8300/tcp"
    - "8301/tcp"
    - "8301/udp"
    - "8302/tcp"
    - "8302/udp"
    - "8400/tcp"
    - "8500/tcp"
  image: consul

consulclient:
  hostname: consulclient
  environment: [CONSUL_MODE=client, CONSUL_SERVER=consulserver, SERVICE=consulclient, DATA_CENTER=dev]
  links:
    - consulserver:consulserver
  ports:
    - "53/tcp"
    - "53/udp"
    - "8300/tcp"
    - "8301/tcp"
    - "8301/udp"
    - "8302/tcp"
    - "8302/udp"
    - "8400/tcp"
    - "8500/tcp"
  image: consul
