FROM ubuntu:15.04
MAINTAINER ml (metaml@gmail.com)

ENV DEBIAN_FRONTEND noninteractive  
RUN locale-gen en_US en_US.UTF-8 && dpkg-reconfigure locales && update-locale LC_ALL="en_US.UTF-8"
RUN apt-get install -y software-properties-common make patch apt-utils
RUN apt-get update -y && apt-get upgrade -y
RUN mkdir -p /data /log && chown -R daemon /data /log

ADD Makefile /var/tmp/Makefile
WORKDIR /var/tmp
RUN make

USER root
ENTRYPOINT ["sleep",  "infinity"]

