#!/bin/sh -x

PATH=/opt/consul:$PATH; export PATH
GOMAXPROCS=8 && export GOMAXPROCS
DATA_CENTER=${DATA_CENTER-local}

ls -l

if [ "server" = "$CONSUL_MODE" ]; then
    BOOTSTRAP_EXPECT=${BOOTSTRAMP_EXPECT-1}
    consul agent -config-dir /opt/consul -server -bootstrap-expect=$BOOTSTRAP_EXPECT
else
    consul agent -config-dir /opt/consul -dc $DATA_CENTER -join $CONSUL_SERVER
fi
