version: '2'
services:
  kafka:
    build: .
    image: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    build: ../zookeeper
    image: zookeeper
  dev-scala:
    build: ../dev-scala
    image: dev-scala
    volumes:
      - /home:/home
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - /etc/sudoers:/etc/sudoer
